name: Build and publish to PyPi

on:
  pull_request:
    branches:
      - main

jobs:
 #  Push a new release to PyPI
  deploy_to_pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    if: github.actor != 'mindsdbadmin'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ vars.CI_PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          pip install .
          pip install setuptools wheel twine build
      - name: Clean previous builds
        run: rm -rf dist/ build/ *.egg-info
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m build
          twine upload dist/*
